from fastapi import APIRouter, Path, File, UploadFile, Form, HTTPException
from typing import Annotated
from datetime import datetime

from domain.repositories import ProjectRepository
from domain.models import ProjectCreation
from service import task_service, save_image

project_repo = ProjectRepository()

router = APIRouter(prefix="/projects", tags=["Project Endpoints"])

# Project endpoints
@router.get("/")
async def get_all_projects():
    """
    Get all projects for debugging purposes
    """
    projects = project_repo.get_all()
    return projects

@router.get("/{id}")
async def get_project(id: str = Path(..., description="Project ID")):
    """
    Get a specific project by ID
    """
    project = project_repo.get_by_id(id)
    return project


@router.get("/{id}/complete")
async def get_project_full(id: str = Path(..., description="Project ID")):
    """
    Get a specific project by ID with all tasks and skills
    """
    project = project_repo.get_by_id(id)
    project.tasks = task_service.get_tasks_with_skills_by_project(id)

    project_dict = project.__dict__
    project_dict["business"] = project_repo.get_business_by_project(id)
    return project_dict


@router.get("/{id}/tasks")
async def get_project_tasks(id: str = Path(..., description="Project ID")):
    """
    Get all tasks for a project
    """
    tasks = task_service.get_tasks_with_skills_by_project(id)
    return tasks

@router.post("/", response_model=ProjectCreation, status_code=201)
async def create_project(
    name: Annotated[str, Form(...)],
    description: Annotated[str, Form(...)],
    supervisor_id: Annotated[str, Form(...)],
    business_id: Annotated[str, Form(...)],
    image: UploadFile = File(...)
):
    """
    Create a new project with image upload
    """
    # Validate required fields
    if not image or not image.filename:
        raise HTTPException(
            status_code=400,
            detail="Een projectafbeelding is verplicht."
        )

    if project_repo.check_project_exists(name, business_id):
        raise HTTPException(
            status_code=400,
            detail=f"Project met de naam '{name}' bestaat al binnen dit bedrijf."
        )

    # Save the image with a random filename
    unique_filename = save_image(image)

    # Create project data
    project_creation = ProjectCreation(
        id=None,  # ID will be generated by repository
        name=name,
        description=description,
        image_path=unique_filename,  # Use the unique filename
        created_at=datetime.now(),
        supervisor_id=supervisor_id,
        business_id=business_id
    )

    # Create the project in the database
    created_project = project_repo.create(project_creation)
    return created_project
