from fastapi import APIRouter, Path, File, UploadFile, Form, HTTPException
from typing import Annotated
from datetime import datetime
from auth.permissions import auth

from domain.repositories import ProjectRepository
from domain.models import ProjectCreation
from service import task_service, save_image
from service.validation_service import is_valid_length

project_repo = ProjectRepository()

router = APIRouter(prefix="/projects", tags=["Project Endpoints"])

# Project endpoints
@router.get("/")
@auth(role="authenticated")
async def get_all_projects():
    """
    Get all projects for debugging purposes
    """
    projects = project_repo.get_all()
    return projects

@router.get("/{project_id}")
@auth(role="authenticated")
async def get_project(project_id: str = Path(..., description="Project ID")):
    """
    Get a specific project by ID
    """
    project = project_repo.get_by_id(project_id)
    return project


@router.get("/{project_id}/complete")
@auth(role="authenticated")
async def get_project_full(project_id: str = Path(..., description="Project ID")):
    """
    Get a specific project by ID with all tasks and skills
    """
    project = project_repo.get_by_id(project_id)
    project.tasks = task_service.get_tasks_with_skills_by_project(project_id)

    project_dict = project.__dict__
    project_dict["business"] = project_repo.get_business_by_project(project_id)
    return project_dict


@router.get("/{project_id}/tasks")
@auth(role="authenticated")
async def get_project_tasks(project_id: str = Path(..., description="Project ID")):
    """
    Get all tasks for a project
    """
    tasks = task_service.get_tasks_with_skills_by_project(project_id)
    return tasks

@router.post("/", response_model=ProjectCreation, status_code=201)
@auth(role="supervisor", owner_id_key="business_id")
async def create_project(
    name: Annotated[str, Form(...)],
    description: Annotated[str, Form(...)],
    supervisor_id: Annotated[str, Form(...)],
    business_id: Annotated[str, Form(...)],
    location: str | None = Form(None),
    image: UploadFile = File(...)
):
    """
    Create a new project with image upload
    """
    if not is_valid_length(name, 100):
        raise HTTPException(
            status_code=400,
            detail="De lengte van de naam moet tussen de 1 en 100 tekens liggen."
        )

    if location and not is_valid_length(location, 255):
        raise HTTPException(
            status_code=400,
            detail="De lengte van de locatie moet tussen de 1 en 255 tekens liggen."
        )

    if not is_valid_length(description, 4000, strip_md=True):
        raise HTTPException(
            status_code=400,
            detail="De lengte van de beschrijving moet tussen de 1 en 4000 tekens liggen."
        )

    # Validate required fields
    if not image or not image.filename:
        raise HTTPException(
            status_code=400,
            detail="Een projectafbeelding is verplicht."
        )

    if project_repo.check_project_exists(name, business_id):
        raise HTTPException(
            status_code=400,
            detail=f"Project met de naam '{name}' bestaat al binnen dit bedrijf."
        )

    # Save the image with a random filename
    unique_filename = save_image(image)

    # Create project data
    project_creation = ProjectCreation(
        id=None,  # ID will be generated by repository
        name=name,
        description=description,
        image_path=unique_filename,  # Use the unique filename
        created_at=datetime.now(),
        business_id=business_id,
        location=location,
        supervisor_id=supervisor_id
    )

    # Create the project in the database
    created_project = project_repo.create(project_creation)
    return created_project

@router.put("/{project_id}")
@auth(role="supervisor", owner_id_key="project_id")
async def update_project(
    project_id: str = Path(..., description="Project ID to update"),
    name: str = Form(...),
    description: str = Form(...),
    location: str | None = Form(None),
    image: UploadFile | None = File(None),
):
    """
    Update project information with optional photo upload.
    Only a teacher or a supervisor of the same business may update the project.
    """
    if not is_valid_length(name, 100):
        raise HTTPException(
            status_code=400,
            detail="De lengte van de naam moet tussen de 1 en 100 tekens liggen."
        )

    if location and not is_valid_length(location, 255):
        raise HTTPException(
            status_code=400,
            detail="De lengte van de locatie moet tussen de 1 en 255 tekens liggen."
        )

    if not is_valid_length(description, 4000, strip_md=True):
        raise HTTPException(
            status_code=400,
            detail="De lengte van de beschrijving moet tussen de 1 en 4000 tekens liggen."
        )

    # Handle photo upload if provided
    image_filename = None
    if image and image.filename:
        try:
            image_filename = save_image(image)
        except Exception as e:
            if hasattr(e, 'status_code'):
                raise HTTPException(status_code=e.status_code, detail=e.detail)
            print(f"Error saving image: {e}")
            raise HTTPException(status_code=500, detail="Er is een fout opgetreden bij het opslaan van de afbeelding")

    try:
        project_repo.update(project_id, name, description, location, image_filename)
        return {"message": "Project succesvol bijgewerkt"}
    except Exception as e:
        if hasattr(e, 'status_code'):
            raise HTTPException(status_code=e.status_code, detail=e.detail)
        print(f"Error updating project: {e}")
        raise HTTPException(status_code=500, detail="Er is een fout opgetreden bij het bijwerken van het project")
